/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



export interface InstanceEntity {
    attributes?: { [key: string]: string; };

    category?: InstanceEntity.CategoryEnum;

    description?: string;

    eGroup?: string;

    instanceId?: number;

    name?: string;

    project?: string;

    type?: string;

    username?: string;

    version?: string;

}
export namespace InstanceEntity {
    export enum CategoryEnum {
        PROD = <any> 'PROD',
        DEV = <any> 'DEV',
        TEST = <any> 'TEST',
        QA = <any> 'QA',
        REF = <any> 'REF'
    }
}
